### ISSUE TITLE
Chunkmaster .jar is being deleted

### ISSUE THREAD

**Issue by JulianInvictus** [Trivernis/spigot-chunkmaster#101]
I'm concerned that it may not have anything to do with Chunkmaster, but instead my own server but regardless I decided to post here. Recently, (past 2 days) every time I've restarted my server, it's deleted the .jar file for Chunkmaster. After scanning the logs, I can't find anything in them that points to the deletion of a whole .jar. I was wondering if you had any advice. I'm currently running Paper 1.16.4, and haven't had issues with it in the past.

**Comment by Trivernis** [comment]
There are server providers that don't allow running chunkmaster and will just delete it.

**Comment by JulianInvictus** [comment]
any way around that?

**Comment by Trivernis** [comment]
I don't know, maybe renaming the jar helps
