### ISSUE TITLE
[QUESTION]Map Generation - "Broken" Bioms "Line"

### ISSUE THREAD

**Issue by nidark** [Trivernis/spigot-chunkmaster#102]
Hello,
I am not sure if this is chunkgenerator issue, but I am trying to understand what went wrong and how I can fix it.

I pregenerated the chunks with chunkmaster and later on I changed to a bigger radius and generate again.
I used dynmap to pregenerate the map a few times as well ..
I am not sure what caused this issue, from one point my bioms are broken ... they dont follow the type of the biome generated before .. see picture. I went there and indeed at that 'line' from the map the next biome is tottaly different .. in the middle of the mountain a ocean .. etc 

So .. do you know what caused this ? .. and how do I fix my map ?
I am using chunkmaster , TerraformGenerator and dynmap ...

Thank you!
![MapCapture](https://user-images.githubusercontent.com/34168906/101281229-319b8b00-37ce-11eb-953e-3bf51ef87076.jpg)

**Comment by Trivernis** [comment]
I don't know what caused this. I can only guess that either for some reason the seed changed after a restart or the custom world generator had a problem.
As for how to fix it: currently the only Idea I've got is to delete the region files that contain the corrupted area.
