### ISSUE TITLE
[Chunkmaster] Task #14 finished after 0 chunks. Bug or my fault ? 

### ISSUE THREAD

**Issue by R0b1S** [Trivernis/spigot-chunkmaster#104]
Not sure if this is bug.

I generated Paper-1.16.5 world from 0,0 to +-7k and everything went fine. Then I needed to generate radius of 2k at position -9000, -8000 so I setCenter at this position. But as I am trying generate command it keeps saying -> [Chunkmaster] Task 14 finished after 0 chunks.

Did I possibly miss something ?

**Comment by Trivernis** [comment]
Did you use chunk coordinates for the center?

**Comment by R0b1S** [comment]
Problem solved, my bad. Closing.

Thank you
