### ISSUE TITLE
Running Chunkmaster produces errors in my server console

### ISSUE THREAD

**Issue by Kenaestic** [Trivernis/spigot-chunkmaster#11]
I'm generating chunks in world and the server console keeps logging these errors:
>.... [04:11:49 ERROR]: Block at 4,637, 31, -8,914 is Block{minecraft:cobblestone} but has net.minecraft.server.v1_14_R1.TileEntitySkull@1a518b84. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
>.... [04:11:49 ERROR]: Block at 4,637, 31, -8,908 is Block{minecraft:cobblestone} but has net.minecraft.server.v1_14_R1.TileEntitySkull@1895f0b5. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
>.... [04:11:49 ERROR]: Block at 4,637, 33, -8,914 is Block{minecraft:cobblestone} but has net.minecraft.server.v1_14_R1.TileEntitySkull@1fdb7141. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
>.... [04:11:49 ERROR]: Block at 4,637, 33, -8,908 is Block{minecraft:cobblestone} but has net.minecraft.server.v1_14_R1.TileEntitySkull@53ebd8b8. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.

What I suspect is Advanced Dungeons is spawning catacombs with mob skulls that are modified somehow and Chunkmaster reading it as a vanilla block.

**Comment by Kenaestic** [comment]
>.... [06:13:24 ERROR]: Block at -894, 50, -9,030 is Block{minecraft:stone_bricks} but has net.minecraft.server.v1_14_R1.TileEntityFurnaceFurnace@2265a4f5. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.
>.... [06:13:24 ERROR]: Block at -894, 50, -9,030 is Block{minecraft:stone_bricks} but has net.minecraft.server.v1_14_R1.TileEntityFurnaceFurnace@2265a4f5. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.

Here's two more.

**Comment by Trivernis** [comment]
This error is related to the chunk generation itself which is only triggered by this plugin. Chunkmaster requests chunks to be loaded the generation itself is handled by the server and therefore unrelated to the plugin.
