### ISSUE TITLE
[question] What is your average speed?

### ISSUE THREAD

**Issue by a3s** [Trivernis/spigot-chunkmaster#12]
I would like to know what generation speed can I expect by using it.
Currently I generate 1.14.4 world on Paper and average is ~22 chunks/sec.
Is it low?

**Comment by Trivernis** [comment]
No, thats about the average speed I get too.

**Comment by a3s** [comment]
OK, thanks.
Great plugin, the ability to generate only on empty server is huge. Works good.

**Comment by resi23** [comment]
i have ~60 with 3 Tasks. 20 per Task
