### ISSUE TITLE
Plugin skips large areas of land when using generate command

### ISSUE THREAD

**Issue by Shawn11564** [Trivernis/spigot-chunkmaster#13]
I’m running the latest version of ChunkMaster on my paperspigot 1.15 server (latest build of paperspigot). I’m using ChunkMaster in tandem with Dynmap to generate a full render of my world map. After setting a worldborder, I began generating the world. If you look at the render: http://54.39.122.230:8092/ you can see it left large chunks of land unfilled. Any idea if I can fix this with config settings?

**Comment by Trivernis** [comment]
If you are using dynmap and generation in parallel it can happen that dynmap skips on some chunks when rendering.
To be safe I'd recommend doing a full render of the map after the chunkmaster generation has finished.

**Comment by Shawn11564** [comment]
Yeah, while doing a fullrender with dynmap it seems to be filling in the gaps. Thanks for the help!
