### ISSUE TITLE
Chunkmaster does not generate anything

### ISSUE THREAD

**Issue by skerit** [Trivernis/spigot-chunkmaster#18]
If I start to generate the world with this command:

```
chunkmaster generate world
[14:01:34 INFO]: Generation task for world world until WorldBorder successfully created
```

Ok, so I list the progress:

```
> chunkmaster list
[14:01:38 INFO]: Currently running generation tasks:
                            - #5 - world - Progress: 0 chunks
```

0 chunks have processed... After a while I get this:

```
[14:01:43 INFO]: [Chunkmaster] Task #5 finished after 0 chunks.
```

Even when I specify a chunk amount, it just does nothing.

I'm running Paper 1.15.2

**Comment by Trivernis** [comment]
Did you change something in the configuration? Did you change the width of the world border?

**Comment by Trivernis** [comment]
Does the error still occur in the latest version? Else I'm going to close this.
