### ISSUE TITLE
Not generating the correct amount of chunks

### ISSUE THREAD

**Issue by itsfolf** [Trivernis/spigot-chunkmaster#19]
I'm attempting to generate a 8000 radius square around my spawn point (-1000, 1000) which should be about 1 million chunks, however, chunkmaster is stopping around halfway through at 566260 chunks. Both the worldborder center and the world spawn point are correctly set to -1000,1000 and the world border is 16000 blocks wide, I can't seem to find any reason that would cause this issue.

Here's the log before the end of the task:
![Screenshot_20200130-075201](https://user-images.githubusercontent.com/9268058/73442454-c5016580-434c-11ea-8645-069150057910.png)

**Comment by fuwwy** [comment]
There's an error right after the ending of the task, perhaps it could be related
![Screenshot_20200130-103445](https://user-images.githubusercontent.com/9268058/73442318-88356e80-434c-11ea-8b66-9da3aff34850.png)

**Comment by Trivernis** [comment]
The only reason for chunkmaster to stop early is reaching the worldborder. I'm investigating if there might be an issue with the checks if the border is reached. For now you could test if it still stops early when setting `ignore-worldborder` in the config to `true`.

**Comment by itsfolf** [comment]
I added some logging to the borderReached method and it ended at chunk `-439 -305` however I teleported there and it's over 2000 blocks away from the border, there's definitely something wrong with how that's calculated

**Comment by Trivernis** [comment]
I think I found the bug.
Basically when converting the chunk coordinates into a location to check if its inside the border I used the x-coordinate instead of the x and z coordinate.
`return Location(world, ((x*16) + 8).toDouble(), 1.0, ((x*16) + 8).toDouble())`

**Comment by itsfolf** [comment]
Ah yes it's always those pesky mistakes 😅 I'm gonna test that

**Comment by itsfolf** [comment]
Seems to be working perfectly now, I'm going to close the issue.
