### ISSUE TITLE
Chunkmaster pregen chunks gone

### ISSUE THREAD

**Issue by Asparasu** [Trivernis/spigot-chunkmaster#24]
Some time ago I successfully pre-generated my 20k by 20k server world. Today I noticed that my server ram was being drained and chunks were loading in slow so I suspected It had something to do with the chunk generation. I installed dynmap and rendered the world, to my surprise only the chunks around spawn and some chunks I flied in before popped up. 

I'm confused how it's possible that the world is no longer pre-generated. Currently the world is being pre-generated again going at the same pace as it did the 1st time I generated it. Any idea what could cause this?

**Comment by Trivernis** [comment]
All the plugin does, is trigger the generation of chunks in a spiral so It's not possible for it to delete chunks. 

Did you confirm that the world was successfully generated when you did it the first time? Is there the possibility that you reset the world to an earlier state?

**Comment by Asparasu** [comment]
![finished](https://user-images.githubusercontent.com/60849647/74105454-2fd94a80-4b5e-11ea-853e-fd285193add6.PNG)

No I never touch the world directory and I don't have any plugins that would be capable of this. On another note, does chunkmaster generate region files? Since the server has a lot of region files that I myself didn't explore.

**Comment by Trivernis** [comment]
No, chunkmaster doesn't generate any files aside from the `chunkmaster.db`to keep track of running tasks and the config file. Did you use the latest version? Because this might be related to #19.

**Comment by Asparasu** [comment]
I will try and see if I have any luck with the latest, im currently on chunkmaster-0.13-beta.

**Comment by Trivernis** [comment]
Okay, let me know :+1:
