### ISSUE TITLE
chunkmaster generating at 10ch/s

### ISSUE THREAD

**Issue by ghost** [Trivernis/spigot-chunkmaster#28]
> [11:23:16] [Server thread/INFO]: [Chunkmaster] 3.999329883908333E7
 [11:23:16] [Server thread/INFO]: [Chunkmaster] Task #1 running for 'world'. Progress: 40346 chunks (0.01%) , ETA: 11109:14:58, Speed: 10.0 ch/s, Last Chunk: -84, 56
as seen here the plugin only generates 10cunks per second, while the processor usage is like 0.2%, in case you need it here is the config file:
`generation:
  period: 2
  chunks-per-step: 100
  chunk-skips-per-step: 100
  mspt-pause-threshold: 1500
  pause-on-join: false
  max-pending-chunks: 100
  max-loaded-chunks: 1000
  ignore-worldborder: false
database:
  filename: chunkmaster.db
language: en`
I am running spigot 1.15.2, no single core is pushed to 100% so it is not a hardware bottleneck

**Comment by Trivernis** [comment]
You could set the config property `period` to one which means that the generation tasks runs every tick instead of every second tick. This should speed things up.
For even better performance I'd recommend to use paper instead of spigot since it handles the loading and saving of chunks asynchronously.

**Comment by cloakfox** [comment]
Having same issue, doesnt matter to what I change the config values, the chunks per second speeds will always stay at 40 ch/s for me.

Edit: atleast this plugin works on paper 👍

**Comment by Trivernis** [comment]
Well about 40 ch/s also is the max speed I've experienced so far. The cause probably is that the generation itself still is single threaded so it's a hardware and design limitation caused by minecraft itself.
