### ISSUE TITLE
UnsatisfiedLinkException caused by shipped copy of sqlite-jdbc

### ISSUE THREAD

**Issue by despair86** [Trivernis/spigot-chunkmaster#30]
paper and spigot already ship it themselves and i had to delete the one in here to avoid `UnsatisfiedLinkException` on a Sun amd64 server (the default sqlite-jdbc does not ship with any DLLs for Oracle hardware)

**Comment by Trivernis** [comment]
This should be solved by making `sqlite-jdbc` a compileOnly dependency, right?
