### ISSUE TITLE
Server spits out stack traces when generating with Realistic World Generator

### ISSUE THREAD

**Issue by Mortderas** [Trivernis/spigot-chunkmaster#34]
Why does the plugin stagger at Cave 5 while pregenerating? I am using Realistic World Generator.
https://mcpaste.io/da15e7bfbe8c220a

**Comment by Trivernis** [comment]
I don't know if this is related to the plugin since it doesn't appear in the logfile at all.
But If it is the reason might be that too many chunks are requested at once (chunks-per-step) which slows the server down. Papers watchdog is noticing that and dumping stack-traces.

**Comment by Mortderas** [comment]
Well I've set it before on one chunk per step

**Comment by Mortderas** [comment]
I've made this change now mspt-pause-threshold: 1000

**Comment by Trivernis** [comment]
What was the previous value?

**Comment by Mortderas** [comment]
500

**Comment by Trivernis** [comment]
In order to decrease lag you should decrease the value since its the maximum time a tick is allowed to take before the generation task pauses.

**Comment by Trivernis** [comment]
Basically just do the opposite of [this guide](https://github.com/Trivernis/spigot-chunkmaster/wiki/Increase-the-generation-speed)

**Comment by Mortderas** [comment]
It works just fine now, the server is under lockdown

**Comment by Trivernis** [comment]
Good to know, so is your question answered by that?

**Comment by Mortderas** [comment]
Skipped 495 lines due to rate limit (500/s) and it's set on 1000

**Comment by Mortderas** [comment]
One second please

**Comment by Mortderas** [comment]
Well there's a problem. When I type /chm list there are no tasks, though if I leave the server, the plugin starts generating again, staggering at the 5th cave. Also, firstly when I saw there's no task, I've assigned another task, smaller this time, and it is not in the list. I think the plugin bugged :/

**Comment by Mortderas** [comment]
After I leave the server it continues the task. https://mcpaste.io/3fa85718b7085ae6

**Comment by Mortderas** [comment]
20.04 09:29:59 [Server] INFO [Chunkmaster] Task #5 running for 'world'. Progress: 73663 chunks (7.35%) , ETA: 0:25:38, Speed: 603.4 ch/s, Last Chunk: 69, 138

**Comment by Mortderas** [comment]
I've set it to 1ch/s but it goes further

**Comment by Mortderas** [comment]
20.04 09:30:29 [Server] INFO [Chunkmaster] Task #5 running for 'world'. Progress: 73707 chunks (7.36%) , ETA: 175:34:43, Speed: 1.5 ch/s, Last Chunk: 113, 138 Now it went back to normal. BUT I must let you know that I've updated Realistic World Generator

**Comment by Trivernis** [comment]
It's that fast because it's skipping chunks until it reaches one that hasn't been generated yet.
Thats also why the speed drops when it has reached chunks that weren't generated yet.
If you don't mind would you send the full log from where you listed all running tasks and where you started the new one.

**Comment by Trivernis** [comment]
If you don't want to paste it here you can also send it to me via mail at support@trivernis.net.

**Comment by Mortderas** [comment]
Mortderas logged in!
20.04 09:35:42 [Server] INFO Mortderas issued server command: /chm list
20.04 09:35:48 [Disconnect] User Mortderas has disconnected, reason: Disconnected
This is in the console

**Comment by Trivernis** [comment]
Hmm, did you do that right after the server started?

**Comment by Mortderas** [comment]
Yes

**Comment by Trivernis** [comment]
Did the plugin report that it has loaded the tasks from the database already? Because the loading of tasks is delayed by 30 sec after the server started to reduce load. This will be changed in the next version but currently its the case.

**Comment by Mortderas** [comment]
No it didn't report, whenever I leave the server, it presents this 
0.04 09:40:08 [Server] INFO [Chunkmaster] Resuming chunk generation task for world 'world'...
20.04 09:40:08 [Server] INFO [Chunkmaster] 1 saved tasks loaded.

**Comment by Trivernis** [comment]
Hmm, I think I need the full logfile to really understand it but my guess is that the tasks weren't loaded when you tried to list them.

**Comment by Mortderas** [comment]
Any idea what are those?
20.04 12:28:18 [Server] Startup 2020-04-20 10:28:18,651 Thread-2 WARN [AsyncContext@70dea4e] Ignoring log event after log4j was shut down.
20.04 12:28:18 [Server] Startup 2020-04-20 10:28:18,652 Thread-2 WARN Ignoring log event after log4j was shut down
20.04 12:28:19 [Server] Startup 2020-04-20 10:28:19,835 pool-51-thread-1 WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger

**Comment by Mortderas** [comment]
And how could I provide you the whole logfile?

**Comment by Trivernis** [comment]
In the `logs` directory of the server there are several logfiles with `latest.log` being the logfile from the latest run of the server. You can attach files in this issue, paste them at pastebin.com or hastebin.com or send them via email.

**Comment by Trivernis** [comment]
> Any idea what are those?
> 20.04 12:28:18 [Server] Startup 2020-04-20 10:28:18,651 Thread-2 WARN [AsyncContext@70dea4e] Ignoring log event after log4j was shut down.
> 20.04 12:28:18 [Server] Startup 2020-04-20 10:28:18,652 Thread-2 WARN Ignoring log event after log4j was shut down
> 20.04 12:28:19 [Server] Startup 2020-04-20 10:28:19,835 pool-51-thread-1 WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger

That seem to be some errors of the apache log4j logger. Might be related to https://issues.apache.org/jira/browse/LOG4J2-658.

**Comment by Mortderas** [comment]
https://hastebin.com/ofelehutis.md

**Comment by Trivernis** [comment]
Hm, so basically every few chunks a chunk takes ages to generate. Since its the generation itself this is most likely related to the Realistic World Generator plugin which also appears in the stack traces. 

As for your issue with the task not being listed, it should be fixed with the next update.

**Comment by Mortderas** [comment]
Then I will contact forward the RWG staff. Thank you for your time and patience!

**Comment by Mortderas** [comment]
Guess who's back
The speed of ch/s is stuck at 1.3 and I've set it up in the config to be around 5 trying to test how much my server's CPU can hold. Any ideas why the config doesn't affect the plugin?

**Comment by Trivernis** [comment]
What does the config look like?

**Comment by Mortderas** [comment]
https://pastebin.com/eNMsQ4BX

**Comment by Trivernis** [comment]
The max-loaded-chunk=1 slows it down significantly since it unloads a chunk every second run instead of generating one.

**Comment by Mortderas** [comment]
Well, I actually have had to change the period

**Comment by Mortderas** [comment]
But your advice was very good

**Comment by Trivernis** [comment]
Oh, I didn't notice, yeah 15 is very slow
