### ISSUE TITLE
[BUG] Don't work generate 

### ISSUE THREAD

**Issue by Saharo4eks** [Trivernis/spigot-chunkmaster#35]
**Describe the bug**
I just went to hell, I've never been here before. Set the border /worldborder. I marked setCenter to your plugin, set it to load /chunk generate world_nether, and it finished it in a second with the words "0 chunks Loaded". In the ordinary world, the same thing happens.

**To Reproduce**
1. /worldborder 21000
2. /chunkm setCenter
3. /chunkm generate world_nether

**Screenshots**
https://imgur.com/qp4LCZo

**Server (please complete the following information):**
 - OS: [e.g. Windows 10 64bit]
 - Specs [e.g. AMD Ryzen5 1600X, 8GB Ram]
 - Java Version [e.g. Java 1.8]
 - Minecraft Server Version [e.g. Paper 1.15.2 #220]
 - Plugin Version [e.g. 0.15beta]

**Comment by Trivernis** [comment]
The world border center uses the block coordinates while the plugin uses chunk coordinates for the center. So you set the chunkmaster center to be outside of the worldborder and it stops immediately.

**Comment by Saharo4eks** [comment]
What can I do to avoid this behavior from the plugin?

**Comment by Trivernis** [comment]
You can set chunkmasters center to 1/16th of the worldborders center coordinates (since a chunk is 16x16 blocks).
