### ISSUE TITLE
Does the plugin keep the progress when restarting the server?

### ISSUE THREAD

**Issue by CyOze** [Trivernis/spigot-chunkmaster#36]
Hello,
I want to generate a world, but sometimes I have to restart my server.
Can I restart my server and continue generating afterwards?
And avoid the generation of an already loaded chunck to save time?
Thanks you in advance.

**Comment by Trivernis** [comment]
@CyOze The plugin stores the progress every 30 seconds and when you shut down the server. It continues pending tasks after the server startup so you can just restart it without worrying about it.

**Comment by CyOze** [comment]
Ok thanks you, This plugin it's so much better than WorldBorder it's a great work thanks you a lot
