### ISSUE TITLE
[FEATURE] Circular Generating

### ISSUE THREAD

**Issue by yimyum** [Trivernis/spigot-chunkmaster#37]
**Is your feature request related to a problem? Please describe.**
WorldBorder plugin has circular generation but it doesn't work anymore due to being dropped.
**Describe the solution you'd like**
I would like circular generation of maps similar to that of worldborder so that I can better fill my dynmap map

**Describe alternatives you've considered**
Adding a border to rendering similar to WorldBorder plugin

**Additional context**
I was generating a world map using ChunkMaster but since my border is circular i was unable to generate it fully. I have to manually fill it now by flying around which is a huge hassle for such an enormous map. Round borders are usually used on towny and civilization servers to help even out the world.

**Comment by Trivernis** [comment]
@yimyum I've got good news for you. I've already implemented circular generation in the develop branch. The reason it's not released yet is that the circle for some reason generates slightly wrong in spigot servers (while it works fine on paper servers).
