### ISSUE TITLE
[BUG] Sqlite Error when creating a task right after startup

### ISSUE THREAD

**Issue by Saharo4eks** [Trivernis/spigot-chunkmaster#40]
Gradually, I expanded the map and started loading, everything went as normal. But at one point, the download just stopped. I thought it was a bug and restarted the server. After that I started the download again and got this error: https://pastebin.com/CXrsnc42

**Comment by Trivernis** [comment]
Wait, how did I miss this issue?
Anyways that stacktrace will be solved in the next update.
It's not related to the stopped loading tho.

**Comment by Trivernis** [comment]
Reopened until its solved by a PR from develop.
