### ISSUE TITLE
[FEATURE] Make the coordinages for setCenter optional and use the player position per default

### ISSUE THREAD

**Issue by Findus642** [Trivernis/spigot-chunkmaster#41]
**Is your feature request related to a problem? Please describe.**
Yes / No. The plugin does support setting the central chunk of the world via the X:Z coordinates. However you are unable to get these coordinates in the plugin alone.

**Describe the solution you'd like**
A command that would allow you to easily get the X:Z coordinates of a chunk. Whilst I was able to obtain these by creating a plugin myself I feel it would be better to have it in the ChunkMaster plugin.

**Describe alternatives you've considered**
Creation of my own plugin - most people might not know how to create a plugin though.

**Additional context**
Nothing.

**Comment by Trivernis** [comment]
I could change the behaviour of the setCenter function to use block coordinates. Also keep in mind that the chunk coordinates are just the world coordinates divided by 16 so you don't have to go as far as creating a plugin to get them.

**Comment by Findus642** [comment]
I suppose having the coordinates as an optional argument could be feasible?

**Comment by Trivernis** [comment]
You mean that it uses the players coordinates by default?

**Comment by Findus642** [comment]
Yes exactly that.
