### ISSUE TITLE
Uncaught exception on chunk unload

### ISSUE THREAD

**Issue by gourdd** [Trivernis/spigot-chunkmaster#46]
**Describe the bug**
While generating chunks these errors came up in console. The commands used were ./chm setCenter world 0 0, ./chm generate world 1500 blockradius, and ./chm resume

**Expected behavior**
I expected this to not happen I guess.

**Screenshots**
https://prnt.sc/sp07v3
https://prnt.sc/sp087w

**Server:**
 - OS: CentOS 7.5
 - Specs [e.g. Intel Xeon E5-2680, 8GB Ram]
 - Java Version 1.15.2
 - Paper 1.15.2
 - 0.15-beta

Prior to now I had tried generating two worlds and got the same error. I'm generating a completely new world and at the moment there's no issue, but before generating I got this warning in console.
https://prnt.sc/sp095j

Thanks

**Comment by aikar** [comment]
This is resolved in latest paper.

**Comment by Trivernis** [comment]
I'll add some additional error handling to the unload handling.
The third warning in the console is related to #40 and will be solved in the the next version.
