### ISSUE TITLE
[QUESTION] Chunkmaster very slow. How to increase speed

### ISSUE THREAD

**Issue by NubeBuster** [Trivernis/spigot-chunkmaster#47]
I'm using chunkmaster on the latest paperspigot version. The chunks per second is only around 10 and my cpu is at around 10%. Any way to drastically increase the cpu usage? I have tried upping the values in config but that doesn't work.

Async chunks is true in paper.yml

**Comment by Trivernis** [comment]
What is your current config?

**Comment by NubeBuster** [comment]
current config is 

`generation:
  period: 1
  chunks-per-step: 100
  chunk-skips-per-step: 100
  mspt-pause-threshold: 2000
  pause-on-join: true
  max-pending-chunks: 1500
  max-loaded-chunks: 2500
  ignore-worldborder: false`

but I have tried many different values. Seeing what would work and what not. The absoulute maximum chunks per second I got was 10

**Comment by Trivernis** [comment]
Hmm, I can't really help you then, that config looks good.

**Comment by 127p** [comment]
> Hmm, I can't really help you then, that config looks good.

Any guide to learn to optimize the plugin?

**Comment by Trivernis** [comment]
@127p Only the config guide

**Comment by 127p** [comment]
@Trivernis I understand, do you have any advice to increase the speed of generation? some proportion among the available options? something to watch out for? any formula to have a good relationship between max loaded chunks, max pending chunks and chunk per step ???
How has it worked best for you, with what settings, etc (??)

**Comment by Trivernis** [comment]
The [example config](https://github.com/Trivernis/spigot-chunkmaster/wiki/Increase-the-generation-speed) in the wiki entry was the fastest for me so far.
In general

`max-pending-chunks = ~ 2*chunks-per-step`, so that there are 2 runs of requesting before the plugin waits for chunks to be loaded.

`max-loaded-chunks = ~ 5*chunks-per-step`, so you only unload all loaded chunks every 5 runs.
