### ISSUE TITLE
[BUG] Stacktrace

### ISSUE THREAD

**Issue by NubeBuster** [Trivernis/spigot-chunkmaster#48]
**Describe the bug**
Chunk generator does not work after a while. Not sure how long. Spams console with error.

**To Reproduce**
Start chunk generator

**Server (please complete the following information):**
 - OS: Ubuntu 20
 - Specs Intel Xeon 3470
 - Java Version OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
 - Minecraft Server Version Paper-318 1.15.2
 - Plugin Version chunkmaster-0.15-beta.jar

**Additional context**
Error log
https://pastebin.com/3DSFAzHi

**Comment by Trivernis** [comment]
This is a [papermc issue](https://github.com/PaperMC/Paper/issues/3459) and solved with a paper v325.
