### ISSUE TITLE
[QUESTION] Chunk speed 0 ch/s

### ISSUE THREAD

**Issue by 127p** [Trivernis/spigot-chunkmaster#49]
Is there any way to avoid that the generation speed per second is more stable?

I am generating an area of ​​20000 block radius in "The end"
CPU fluctuates around 30% and 99% all the time

The server is running in paper 1.15.2 b.333
Settings: 
period: 2
chunks-per-step: 500
chunk-skips-per-step: 500
 max-loaded-chunks: 500
max-pending-chunks: 1000
mspt-pause-threshold: 500

These are the only options that have allowed me to reach a speed of 50chunks per second
![Screenshot_3](https://user-images.githubusercontent.com/57081715/83569076-f738f480-a4f1-11ea-90b0-32dd0d58e543.png)

![Screenshot_4](https://user-images.githubusercontent.com/57081715/83569175-146dc300-a4f2-11ea-83e9-ae2164f053b3.png)

**Comment by Trivernis** [comment]
Can you give me a full logfile?

**Comment by 127p** [comment]
Here is the log for the end with the settings that i mention before
[2020-06-02-8.log.gz](https://github.com/Trivernis/spigot-chunkmaster/files/4742514/2020-06-02-8.log.gz)
[2020-06-02-9.log.gz](https://github.com/Trivernis/spigot-chunkmaster/files/4742515/2020-06-02-9.log.gz)

Here you can see how finish the task for the end and then start the task for the overworld with other settings:
period: 2
  chunks-per-step: 500
  chunk-skips-per-step: 500
  max-loaded-chunks: 1000
  max-pending-chunks: 1000
  mspt-pause-threshold: 500
[2020-06-03-1.log.gz](https://github.com/Trivernis/spigot-chunkmaster/files/4742510/2020-06-03-1.log.gz)
[2020-06-03-2.log.gz](https://github.com/Trivernis/spigot-chunkmaster/files/4742512/2020-06-03-2.log.gz)
As you can see, the task for the overworld is a lot stable but extremely slow in compare with the task for the end

I Hope you can help me to get this work properly

**Comment by Trivernis** [comment]
Oh, I think the speed variation is because the plugin pauses the generation when the mspt is higher than 500 ms. So my guess is that thats the reason it reported 0 ch/s
