### ISSUE TITLE
[QUESTION] Is there any way to get the generation to go up until the worldborder border, and not over it ?

### ISSUE THREAD

**Issue by bastobasto** [Trivernis/spigot-chunkmaster#50]
**Question**

Is there any way to get the generation to go up until the worldborder border, and not over it  ?

**Additional context**

I'm using worldborder for the context of doing a round Earth thanks to the wrap feature, but the chunk outside the border keep generating ( Using chunkmaster of course ). It's a rectangular custom map so i'm not sure the vanilla one could do it correctly.

**Comment by Trivernis** [comment]
the plugin can't generate rectangular but you could generate two squares to get a rectangle.
1. set the first center: chm setCenter world <chunk X> <chunk Z>
2. generate until the world border radius: chm generate world <radius> blockradius
3. set the second center: chm setCenter world <chunk X> <chunk Z>
4. same as 2.

**Comment by Trivernis** [comment]
or use wb fill

**Comment by bastobasto** [comment]
Am I supposed to do fullrender after doing generate ? Because it isn't working

**Comment by Trivernis** [comment]
Dynmap probably isn't finished, it takes way longer to render the map than to generate it.
