### ISSUE TITLE
[QUESTION] How to increase and skip all the already generated chunks faster?

### ISSUE THREAD

**Issue by johnsoncui02** [Trivernis/spigot-chunkmaster#52]
How to increase and skip all the already generated chunks faster?

I have generated a 15k x 15k map and I want to increase it to 20k x 20k.
What kind of settings would enable me to scan the already generated chunks faster?
or is the plugin already doing that itself?

**Comment by Trivernis** [comment]
Increase the value of the chunk-skips-per-step setting which is literally the number of chunks that are being skipped.
