### ISSUE TITLE
[QUESTION] Running ChunkMaster on a live server

### ISSUE THREAD

**Issue by johnsoncui02** [Trivernis/spigot-chunkmaster#53]
I, I was wondering if or anyone has the minimal settings for running chunkmaster while players are online? Currently I've tried very low settings but yet it is still dropping TPS for some reason. If anyone has suggestions on and if this can be done without dropping TPS heavily please do let me know.

Here is my current settings (which still lags)
https://pastebin.com/raw/U6W3d1aj

**Comment by Trivernis** [comment]
Set chunks-per-step to 1 and mspt-pause-threshold to 50

**Comment by Trivernis** [comment]
With Release 1.0 I've added an option to pause when a specific number of players are online, so that might help you as well.
