### ISSUE TITLE
How can i increase the map from 10000x10000 to 12500x12500 without increasing the worldborder?

### ISSUE THREAD

**Issue by Snukkieboy** [Trivernis/spigot-chunkmaster#54]
How can i increase the map from 10000x10000 to 12500x12500 without increasing the worldborder?

How can i increase the map without moving the border because when i try /chm generate world 610351. it will stop when it hits the worldborder

**Comment by Trivernis** [comment]
In the config file set `ignore-worldborder` to `true`
