### ISSUE TITLE
[BUG] Crash quickly after starting a pregen job [1.16.1]

### ISSUE THREAD

**Issue by jinkhya** [Trivernis/spigot-chunkmaster#57]
**Describe the bug**
After starting a pregen task (with a 10000 blocks radius in the nether) it crashes

**To Reproduce**
Run /chunkmaster generate world_nether 10000
Wait for a couple minutes and it crashes

**Expected behavior**
Not to crash :)

**Screenshots**

**Server (please complete the following information):**
 - OS: CentOS Linux 7
 - Specs [Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz]
 - Java Version [1.8.0_212]
 - Minecraft Server Version [Spigot 1.16.1]
 - Plugin Version [0.16]

**Additional context**
Crash report : https://paste.gg/p/anonymous/ae14aea54ca74f6c98f7ca6a9d9921f8

**Comment by Trivernis** [comment]
Oh, I've encountered that one. I think it's a bukkit bug so you should report it there too.

**Comment by Trivernis** [comment]
@Trivernis Uhm, I think my reply was a bit verbose

**Comment by jinkhya** [comment]
ok I'll open an issue and link this thread :)

**Comment by jinkhya** [comment]
done : https://hub.spigotmc.org/jira/browse/SPIGOT-5838

**Comment by Trivernis** [comment]
Great, I'll leave this issue open until we've got further information

**Comment by Trivernis** [comment]
Resolved as SPIGOT-5926
