### ISSUE TITLE
[BUG] Incorrect percentage of total chunk generated & ETA Time

### ISSUE THREAD

**Issue by Rend-Creator** [Trivernis/spigot-chunkmaster#61]
**Describe the bug**
There is a weird bug that the percentage of total chunk generated seems to be off or fluctuating and ETA time at which the chunk generation will be complete. (although it doesn't affect the chunk generated totality just visual bug.)

**To Reproduce**
1. Generate a world.

**Expected behavior**
The expected result should have a concise percentage of  total chunk generated and correct ETA time.

**Screenshots**
Here's the sample screenshot, the highlighted part is the problem:
![image](https://user-images.githubusercontent.com/61183625/85939123-90b6c300-b945-11ea-90d0-26067f1818d2.png)

**Server (please complete the following information):**
 - OS: Windows 10 Build 2004
 - Specs: Ryzen 7 2700U, RX 560X, 16 GB
 - Java Version: Java 8
 - Minecraft Server Version: Paper 1.16.1 Build 2
 - Plugin Version: Chunk Master 1.0

**Additional context**
Nothing more...

**Comment by Trivernis** [comment]
@Rend-Creator What was the exact command you've used?
Or at least, which shape did you use?

**Comment by Rend-Creator** [comment]
chm generate nether_world 2500, Also I used square by default
