### ISSUE TITLE
Fatal Error PaperSpigot#10 1.16.1[BUG]

### ISSUE THREAD

**Issue by Saharo4eks** [Trivernis/spigot-chunkmaster#62]
Hellow, I'm started generate world_nether on my server and see this fatal error

**Server (please complete the following information):**
 - Specs [e.g. Ryzen5 1400, 12GB Ram]
 - Java Version [e.g. Java 1.9]
 - Minecraft Server Version [e.g. Paper 1.16.1 #10]
 - Plugin Version [e.g. 1.0]

ERROR: https://pastebin.com/piNNvgvM

**Comment by Trivernis** [comment]
That looks like an issue of paper itself to me. Please report it in the Paper repository https://github.com/PaperMC/Paper/issues

**Comment by Trivernis** [comment]
https://github.com/PaperMC/Paper/issues/3658

**Comment by leasoncre** [comment]
i'm seeing this too, though i believe it happened when i tried to stop the server.
Paper-24 (1.16)
[latest.log](https://github.com/Trivernis/spigot-chunkmaster/files/4848304/latest.log)
EDIT: no, it just happens after about 30 min or so... sometimes ticklags the server, but 1.16 still beta imo

**Comment by Trivernis** [comment]
@leasoncre Add your issue to the Paper issue I've linked above

**Comment by Trivernis** [comment]
The paper issue has been solved
