### ISSUE TITLE
[BUG] Generate Map 1.16

### ISSUE THREAD

**Issue by Saharo4eks** [Trivernis/spigot-chunkmaster#64]
Hi, a generate my map and recieve this error: https://pastebin.com/7arSgN5M

PaperSpigot#10 1.16.1 
Windows 10
Ryzen5 1400, 8GB RAM

**Comment by Trivernis** [comment]
That one is most likely not related to chunkmaster but either a paper or a vanilla bug.
Does it affect the server in some way?

**Comment by Saharo4eks** [comment]
Nope, but this error. 
I tell Paper's team for this

**Comment by Johnibur** [comment]
This issue is occasionally happening on Spigot as well.

**Comment by Trivernis** [comment]
Well then I guess It needs to get reported to mojang

**Comment by Trivernis** [comment]
Since there was no further information about this and because it's not directly related to the plugin, I'm closing the issue now.
