### ISSUE TITLE
[BUG] Task restarts from 0% after restarting server

### ISSUE THREAD

**Issue by Neitex** [Trivernis/spigot-chunkmaster#66]
Chunkmaster starts world generation from 0% after restarting server properly (with stop command.)
Steps to reproduce: 
1. Start world generation
2. Wait some time
3. Stop server w/ stop command
4. Run server again

Latest build from Spigotmc.org
Win10 Pro 16GB

**Comment by Trivernis** [comment]
@Neitex Can you attach a log file with the error occuring?

**Comment by kaanakduman** [comment]
I also had the issue, but I didn't even stop the server. I simply paused and resumed it. I'm on Purpur-640. I can reliably reproduce the issue on my server. Simply pausing the generation and then resuming it resets it to 0%.
![image](https://user-images.githubusercontent.com/33491458/86882631-31c81b00-c0b6-11ea-914f-86068991fce6.png)

>.... [01:57:52 INFO]: DrBot issued server command: /chunkmaster list
>.... [01:57:54 INFO]: DrBot issued server command: /chunkmaster list
>.... [01:57:59 INFO]: DrBot issued server command: /chunkmaster list
>.... [01:58:03 INFO]: DrBot issued server command: /chunkmaster list
>.... [01:58:06 INFO]: DrBot issued server command: /chunkmaster pause
>.... [01:58:06 INFO]: [Chunkmaster] Saving the progress of task #7 to the database...
>.... [01:58:06 INFO]: [Chunkmaster] Canceled task #7.
>.... [01:58:10 INFO]: DrBot issued server command: /chunkmaster list
>.... [01:58:13 INFO]: DrBot issued server command: /chunkmaster resume
>.... [01:58:13 INFO]: [Chunkmaster] Resuming chunk generation task for world 'world'...
>.... [01:58:13 INFO]: [Chunkmaster] 1 saved tasks loaded.
>.... [01:58:14 INFO]: DrBot issued server command: /chunkmaster list

**Comment by Trivernis** [comment]
Theres a problem that the initial progress value is always 0 because the task hasn't run and checked the progress yet. Could this be related?

**Comment by Neitex** [comment]
> 
> 
> Theres a problem that the initial progress value is always 0 because the task hasn't run and checked the progress yet. Could this be related?

In my case, one time it ran 8 hours straight, and still checking chunks after restart.



> 
> 
> @Neitex Can you attach a log file with the error occuring?

Sure. [https://paste.ubuntu.com/p/fZVKqffXSS/](urll)

P.S. Today I encountered another problem, but now it says " [Chunkmaster] Task #368 for Chunkmaster v1.0.1 generated an exception" and crashed server.  Should i create another issue?

**Comment by Trivernis** [comment]
Okay, looks like that might really be a bug.
Ill look into it, my guess is that it only affects spigot.
Please open a new issue for the other problem, so I can keep better track of it.

**Comment by handryck** [comment]
> Okay, looks like that might really be a bug.
> Ill look into it, my guess is that it only affects spigot.
> Please open a new issue for the other problem, so I can keep better track of it.

I can confirm that's the same issue with Paper 1.16.1 build #71.
Either after restart or pause/resume.

**Comment by Trivernis** [comment]
Can you please attach your servers database file (chunkmaster.db in the plugins folder) after the plugin has been running for some time?

**Comment by handryck** [comment]
Hello. I saw you need the chunkmaster.db file but you closed the issue. Is it still needed? I will send it soon.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Trivernis** [comment]
It's not needed anymore but thanks for your reply
