### ISSUE TITLE
[BUG] It does not work if the name of the world is only from numbers

### ISSUE THREAD

**Issue by dalandis** [Trivernis/spigot-chunkmaster#67]
**Describe the bug**
It does not work if the name of the world is only from numbers

**To Reproduce**
1. in server.properties specify level-name = 2015
2. start server
3. run in server console 'chunkmaster generate 2015'
4. get the World '2015' not found!

**Expected behavior**
The world was expected to be generated

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - Specs Intel(R) Xeon(R) CPU E5-2630 v4, 32Gb RAM
 - Java Version Java 1.8
 - Minecraft Server Version Paper 1.16.1
 - Plugin Version 1.0.1

**Comment by Trivernis** [comment]
Can you send me a logfile for this?
My guess is that the server interprets the name as a radius and says that you need to specify a world name.

**Comment by dalandis** [comment]
After entering the "chunkmaster generate 2015" command, I get the message "You need to provide a world name!" or "World '2015' not found!"

I also tried to specify the name of the world in quotes and back quotes, but the result is the same

<img width="1135" alt="Снимок экрана 2020-07-09 в 11 05 05" src="https://user-images.githubusercontent.com/15212686/87008038-31be3d00-c1d4-11ea-98b6-07fece7e74ce.png">
<img width="732" alt="Снимок экрана 2020-07-09 в 11 07 31" src="https://user-images.githubusercontent.com/15212686/87008225-7a75f600-c1d4-11ea-8c0b-bccd9fb9e2e8.png">

**Comment by Trivernis** [comment]
@dalandis Should be fixed with the next version

**Comment by Trivernis** [comment]
Fixed in #71
