### ISSUE TITLE
[BUG] Chunkmaster crashes server

### ISSUE THREAD

**Issue by Neitex** [Trivernis/spigot-chunkmaster#68]
**Describe the bug**
After some time running generation task, server crashed

**To Reproduce**
I don't know how to reproduce it.

**Server (please complete the following information):**
 - OS: Win10 Pro
 - Specs: I5-9400F, 16GB (minecraft allocated 14GB)
 - Java Version: AdoptOpenJDK JRE w/Hotspot 11.0.7.10 (x64)
 - Minecraft Server Version: git-Paper-71 (MC: 1.16.1)
 - Plugin Version: 1.0.1

Log: [https://paste.ubuntu.com/p/PKFNwMx8Vq/](url)

**Comment by Trivernis** [comment]
Oh, that one is not really related to chunkmaster but to papers async chunk generation. If it still ocures in the latest paper, report it to them.
