### ISSUE TITLE
[BUG] Task restarts from 0% after pausing due to playercount

### ISSUE THREAD

**Issue by bdnugget** [Trivernis/spigot-chunkmaster#70]
**Describe the bug**
When the task gets paused because of players joining, and resumes after they leave, it starts from 0% again.
Sometimes (if a lot more players have joined) it doesn't resume automatically and claims to have been paused manually. Manually resuming still makes it start at 0%.

[Screenshot](https://i.imgur.com/T3PtJUN.png)

**Server (please complete the following information):**
 - OS: Debian 9
 - Specs Intel(R) Xeon(R) CPU E5-2630 v3 16 cores @ 2.40GHz, 8GB
 - Java Version Openjdk version "1.8.0_252"
 - Minecraft Server Version Spigot 1.16.1
 - Plugin Version `1.0.1

**config.yml**
generation:
  period: 2
  chunks-per-step: 2
  chunk-skips-per-step: 100
  mspt-pause-threshold: 500
  pause-on-player-count: 1
  max-pending-chunks: 10
  max-loaded-chunks: 10
  ignore-worldborder: false
database:
  filename: chunkmaster.db
language: en
dynmap: false

**Comment by Trivernis** [comment]
Can you please attach the log file and the chunkmaster.db file (in the plugins folder) after it has been running for a bit?
