### ISSUE TITLE
[BUG] Error messages when generating new chunks on 1.16.1

### ISSUE THREAD

**Issue by Dragonber1** [Trivernis/spigot-chunkmaster#74]
**Describe the bug**
Chunkmaster sends error messages when new chunks are generated.

**To Reproduce**
1. Add Chunkmaster to plugins folder
2. Start the server
3. Create a Chunkmaster task specifically: /chunkmaster generate world 10000 square
4. See error when new chunks are generated, generation just keeps going and sending errors.

**Expected behavior**
Chunks generate without errors on console.

**Screenshots**
![image](https://user-images.githubusercontent.com/65039705/87612607-4be3a800-c70b-11ea-9754-27f44a5595f5.png)

**Logfile**
https://pastebin.com/0Pfbv4SJ

**Server (please complete the following information):**
 - OS: Ubuntu server 20.04, Pterodactyl panel
 - Specs: AMD Ryzen 7 2700, 16GB RAM
 - Java Version: OpenJDK 1.8.0_242
 - Minecraft Server Version: Paper 1.16.1 #91
 - Plugin Version: 1.2.1

**Additional context**
New server installation with default config except for bungeecord specific settings. Chunkmaster is the only plugin used. The server world is converted from a 1.15.2 server using --forceUpgrade. The server works, players can enter and generate terrain.

**Comment by Trivernis** [comment]
That issue is probably a paper or even vanilla issue. My suggestion is that you report it to paper.

**Comment by Dragonber1** [comment]
Found the issue, it was unrelated to chunkmaster. The world was corrupted, wouldn't have found out without using chunkmaster, so thanks.

Edit, I was wrong, the world is not corrupted, it’s a known bug with older minecraft version villages converted to minecraft 1.16. Using mcaedit to delete the regions and generating them again fixes the problem.
