### ISSUE TITLE
[BUG] Task seems not resuming automatically after 1+ players joined and quited

### ISSUE THREAD

**Issue by NPBeta** [Trivernis/spigot-chunkmaster#89]
**Describe the bug**
I set `pause-on-player-count` to 1 in the config. If there is only one player joined server and then quited, the task will auto pause and resume properly. However, if 2 or more players joined and quited, I just get `Generate progress is manually paused` message in the console. Don't know what happen if the value is not 1.

**To Reproduce**
1. Start the server with `pause-on-player-count` setted to 1
2. Make sure the generate task is running
3. Make 2 or more players online at the same time (now the task automatically paused)
4. All players quit the server
5. Generation will not be resumed automatically

**Expected behavior**
Generation will not be resumed automatically, and Console output `Generation was manually paused. Not resuming automatically.`

**Server (please complete the following information):**
 - OS: Not sure, Running in Dockers
 - Specs: 3vCores / 6GB RAM
 - Java Version: 1.8, OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
 - Minecraft Server Version: Paper 1.16.1 Build #121
 - Plugin Version: 1.3.1

**Comment by NPBeta** [comment]
In addition, there is always a TASK CANCEL FAILED warning when `The player count has reached the pause value. Pausing generation...`. I'm sure the task has been cancelled and saved properly because the task always resumes at where it has been paused.

**Comment by NPBeta** [comment]
> In addition, there is always a TASK CANCEL FAILED warning when `The player count has reached the pause value. Pausing generation...`. I'm sure the task has been cancelled and saved properly because the task always resumes at where it has been paused.

That will cause server main thread blocking too.
Stacktrace by Paper:
![image](https://user-images.githubusercontent.com/17808640/88762443-c8629600-d1a3-11ea-9f90-d6bf2e950502.png)

**Comment by Trivernis** [comment]
I'll look into the problems with the pausing. The error with the task not being stopped is related to a maximum amount of milliseconds the main thread waits for the generation task to be stopped. It shouldn't be critical.
The screenshot you've attached in the latest message seems to be related to a different plugin.

**Comment by NPBeta** [comment]
> The screenshot you've attached in the latest message seems to be related to a different plugin.

Sorry I take a wrong screenshot. I cannot find the correct Stacktrace now because I've clear the console output. If it shows again I will put it here to help you find the cause and fix it. Thanks!

> It shouldn't be critical.

Yes. Data can be saved although the warning shows.

**Comment by Trivernis** [comment]
You could check the logfiles

**Comment by NPBeta** [comment]
![image](https://user-images.githubusercontent.com/17808640/88776031-0964a580-d1b8-11ea-8b58-0c7c553dfc23.png)
Text Version: [Pastebin](https://paste.ubuntu.com/p/ySP4WTByVf/)

and Another one:
![image](https://user-images.githubusercontent.com/17808640/88776157-3022dc00-d1b8-11ea-8e15-47d8be72b655.png)
Also text version: [Pastebin](https://paste.ubuntu.com/p/y5hfHdDBrX/)
