### ISSUE TITLE
[BUG] Missing Percentage and ETA in Console Output

### ISSUE THREAD

**Issue by NPBeta** [Trivernis/spigot-chunkmaster#90]
**Describe the bug**
The progress message nolonger shows generate percentage and ETA.

**To Reproduce**
1. Create a task
2. Start the task
3. Wait Progress message shows in console
4. See the message

**Expected behavior**
No percentage or ETA is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/17808640/88744430-eca97d00-d179-11ea-9d79-e26f1df21f3f.png)

**Server (please complete the following information):**
 - OS: Not sure, Running in Dockers
 - Specs: 3vCores / 6GB RAM
 - Java Version: 1.8, OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
 - Minecraft Server Version: Paper 1.16.1 Build #121
 - Plugin Version: 1.3.1

**Additional context**
I've checked the I18N file and there is `%s %s`. The message can be shown correctly before 1.3.0.

**Comment by Trivernis** [comment]
Does the task generate until the worldborder?

**Comment by NPBeta** [comment]
> Does the task generate until the worldborder?

Yes, I didn't define the range in the command. I just executed `/chm generate <worldname>`.

**Comment by Trivernis** [comment]
Oh, then I can understand what happens.
Currently the eta and progress is only shown for tasks with a defined radius since the coordinates providing shape returns the progress.
