### ISSUE TITLE
[FEATURE] Completed radius size from chm stats <world>

### ISSUE THREAD

**Issue by DiegoDaniel** [Trivernis/spigot-chunkmaster#93]
**Is your feature request related to a problem? Please describe.**
Is it possible to add, based on the % completed, an "approximate value" of the radious size completed from the Origen?

**Describe the solution you'd like**
Let's say i'm pre generating 10k radious.
When i run /chm stats world, i would like to see something like 
world_nether
- 69 Entities
- 540 Loaded Chunks
- Generating: true (this would be great also)
   - CompletedRadiousTask3: 8709 chunks from [x ; z] 74.4%
- Validating: false
- CompletedTasks:
   - Task1: 5000 Radious from [ x;z ]
   - Task2: 10000 Radious from [ x;z ]

Hope you likes this idea

**Comment by Trivernis** [comment]
Since you can already see the running tasks with the `chm list` command, I'm just adding a field for if the generation is running in the world. For the completed tasks I'm adding a separate command.
